#ifndef RSMLAYOUT_H
#define RSMLAYOUT_H

#include <glad/glad.h>
#include <GLFW/glfw3.h>
#include <stdint.h>

#define WINDOW_WIDTH 1920
#define WINDOW_HEIGHT 1080
#define WINDOW_NAME "Redsim V0.1"

extern float RSM_FLY_X_ACCELERATION;
extern float RSM_FLY_Y_ACCELERATION;
extern float RSM_FLY_Z_ACCELERATION;
extern float RSM_FLY_FRICTION;
extern float RSM_FLY_SPEED_CAP;

#define RSM_KEY_MENU GLFW_KEY_ESCAPE
#define RSM_KEY_INVENTORY GLFW_KEY_E
#define RSM_KEY_COMMAND GLFW_KEY_T
#define RSM_KEY_FORWARD GLFW_KEY_W
#define RSM_KEY_BACKWARD GLFW_KEY_S
#define RSM_KEY_RIGHT GLFW_KEY_D
#define RSM_KEY_LEFT GLFW_KEY_A
#define RSM_KEY_DOWN GLFW_KEY_LEFT_SHIFT
#define RSM_KEY_UP GLFW_KEY_SPACE
#define RSM_BUTTON_LEFTCLICK GLFW_MOUSE_BUTTON_LEFT
#define RSM_BUTTON_RIGHTCLICK GLFW_MOUSE_BUTTON_RIGHT
#define RSM_BUTTON_MIDDLECLICK GLFW_MOUSE_BUTTON_MIDDLE

#define RSM_KEY_HOTSLOT0 GLFW_KEY_1
#define RSM_KEY_HOTSLOT1 GLFW_KEY_2
#define RSM_KEY_HOTSLOT2 GLFW_KEY_3
#define RSM_KEY_HOTSLOT3 GLFW_KEY_4
#define RSM_KEY_HOTSLOT4 GLFW_KEY_5
#define RSM_KEY_HOTSLOT5 GLFW_KEY_6
#define RSM_KEY_HOTSLOT6 GLFW_KEY_7
#define RSM_KEY_HOTSLOT7 GLFW_KEY_8
#define RSM_KEY_HOTSLOT8 GLFW_KEY_9
#define RSM_KEY_HOTSLOT9 GLFW_KEY_0

extern float RSM_MOUSE_SENSITIVITY;

#define RSM_HOTBAR_SLOTS 10
#define RSM_HOTBAR_COUNT 2

extern float RSM_FPS;
#define FPS_CAP true

extern float RSM_FOV;
extern unsigned int RENDER_DISTANCE;
extern float RENDER_DISTANCE_NEAR;
#define CHUNKSIZE 32

#define PLAYER_BOUNDINGBOX_RELATIVE_CORNER ((vec3) {-0.3f, -1.6f, -0.3f})
#define PLAYER_BOUNDINGBOX_DIMENSIONS ((vec3) {0.6f, 1.8f, 0.6f})
#define BLOCK_BOUNDINGBOX_SAFE_DISTANCE 1e-4f

#define RSM_BLOCK_TEXTURE_SIZE_PIXELS 32
#define RSM_GUI_TEXTURE_SIZE_PIXELS 64
#define RSM_SPRITE_TEXTURE_SIZE_PIXELS 16
/* Offset should be calculated as if rendering without scaling, as it will adjust automatically */
#define RSM_SPRITE_OFFSET_PIXELS 10
#define RSM_GUI_SCALING_FACTOR 1.0f

#define RSM_MAX_BLOCKMESH_VERTICES 10000
#define RSM_MAX_BLOCKMESH_INDICES 30000
#define RSM_MAX_PATH_NAME_LENGTH 512
#define RSM_MAX_SHADER_INFOLOG_LENGTH 512

#define RSM_BIT_COLLISION (1UL << 0) /* Collidable */

extern char textureBasePath[10];
extern char textureBlockPath[8];
extern char textureGuiPath[5];
extern char textureBlockmapPath[13];
extern char textureGuimapPath[11];
extern char meshFormatExtension[6];
extern char textureFormatExtension[5];
extern char boundingboxFormatExtension[13];

typedef enum RSM_EXITCODE {
	RSM_EXIT_NORMAL = 0,
	RSM_EXIT_EXCBUF,
	RSM_EXIT_NOBLOCKMAP,
	RSM_EXIT_NOMESHDATA,
	RSM_EXIT_NOBOUNDINGBOXDATA,
	RSM_EXIT_NOTEXTURE,
	RSM_EXIT_BADTEXTURE,
	RSM_EXIT_BADVERTEXDATA,
	RSM_EXIT_BADBOUNDINGBOXDATA
} RSM_EXITCODE;

#endif
