#ifndef RSMLAYOUT_H
#define RSMLAYOUT_H

#include <glad/glad.h>
#include <GLFW/glfw3.h>
#include <stdint.h>

#define DEFAULT_SCREEN_WIDTH 1920
#define DEFAULT_SCREEN_HEIGHT 1080
#define WINDOW_NAME "Redsim V0.8"

extern float RSM_FLY_ACCELERATION;
extern float RSM_FLY_X_ACCELERATION;
extern float RSM_FLY_Y_ACCELERATION;
extern float RSM_FLY_Z_ACCELERATION;
extern float RSM_FLY_FRICTION;
extern float RSM_FLY_SPEED_CAP;

#define RSM_KEY_CTRL_EXIT GLFW_KEY_Q
#define RSM_KEY_MENU GLFW_KEY_ESCAPE
#define RSM_KEY_INVENTORY GLFW_KEY_E
#define RSM_KEY_COMMAND 0x74 /* ASCII 't' */
#define RSM_KEY_CTRL_CLEARLOG GLFW_KEY_R
#define RSM_KEY_FORWARD GLFW_KEY_W
#define RSM_KEY_BACKWARD GLFW_KEY_S
#define RSM_KEY_RIGHT GLFW_KEY_D
#define RSM_KEY_LEFT GLFW_KEY_A
#define RSM_KEY_DOWN GLFW_KEY_LEFT_SHIFT
#define RSM_KEY_UP GLFW_KEY_SPACE
#define RSM_BUTTON_LEFTCLICK GLFW_MOUSE_BUTTON_LEFT
#define RSM_BUTTON_RIGHTCLICK GLFW_MOUSE_BUTTON_RIGHT
#define RSM_BUTTON_MIDDLECLICK GLFW_MOUSE_BUTTON_MIDDLE

#define RSM_COMMAND_PREFIX ":"

#define RSM_KEY_HOTBAR_INCREMENT GLFW_KEY_X
#define RSM_KEY_HOTBAR_DECREMENT GLFW_KEY_Z
#define RSM_KEY_HOTSLOT0 GLFW_KEY_1
#define RSM_KEY_HOTSLOT1 GLFW_KEY_2
#define RSM_KEY_HOTSLOT2 GLFW_KEY_3
#define RSM_KEY_HOTSLOT3 GLFW_KEY_4
#define RSM_KEY_HOTSLOT4 GLFW_KEY_5
#define RSM_KEY_HOTSLOT5 GLFW_KEY_6
#define RSM_KEY_HOTSLOT6 GLFW_KEY_7
#define RSM_KEY_HOTSLOT7 GLFW_KEY_8
#define RSM_KEY_HOTSLOT8 GLFW_KEY_9
#define RSM_KEY_HOTSLOT9 GLFW_KEY_0

extern float RSM_MOUSE_SENSITIVITY;

#define RSM_HOTBAR_SLOTS 10
#define RSM_HOTBAR_COUNT 2

#define RSM_INVENTORY_SLOTS_HORIZONTAL 12
#define RSM_INVENTORY_SLOTS_VERTICAL 2
#define RSM_INVENTORY_SUBMENUS 4

#define RSM_FPS 240.0f
#define FPS_CAP true
#define VSYNC true

#define CHUNKSIZE 32
extern float RSM_REACH;
extern float RSM_FOV;
extern float RSM_LOADING_DISTANCE;
extern float RSM_RENDER_DISTANCE;
extern float RSM_NEARPLANE;

extern float RSM_COMMAND_POS_X_PIXELS;
extern float RSM_COMMAND_POS_Y_PIXELS;
extern float RSM_COMMAND_TEXT_SIZE;

#define PLAYER_BOUNDINGBOX_RELATIVE_CORNER ((vec3) {-0.3f, -1.6f, -0.3f})
#define PLAYER_BOUNDINGBOX_DIMENSIONS ((vec3) {0.6f, 1.8f, 0.6f})

#define RSM_TEXTURE_PADDING 0.01f
#define RSM_BLOCK_TEXTURE_SIZE_PIXELS 32
#define RSM_GUI_TEXTURE_SIZE_PIXELS 64
#define RSM_SPRITE_TEXTURE_SIZE_PIXELS 16
#define RSM_CHARACTER_TEXTURE_SIZE_PIXELS 32

extern float RSM_DEFAULT_GUI_SCALING_FACTOR;
#define RSM_GUI_SCALING_FACTOR (RSM_DEFAULT_GUI_SCALING_FACTOR \
	* (((float)screenWidth/DEFAULT_SCREEN_WIDTH + (float) screenHeight/DEFAULT_SCREEN_HEIGHT)/2.0f))
#define RSM_CROSSHAIR_SIZE_PIXELS (RSM_GUI_SCALING_FACTOR * 32)
#define RSM_HOTBAR_SLOT_SIZE_PIXELS (RSM_GUI_SCALING_FACTOR * 64)
#define RSM_INVENTORY_SLOT_SIZE_PIXELS (RSM_GUI_SCALING_FACTOR * 64)
#define RSM_INVENTORY_ICON_SIZE_PIXELS (RSM_INVENTORY_SLOT_SIZE_PIXELS \
		* (RSM_INVENTORY_SLOTS_HORIZONTAL / RSM_INVENTORY_SUBMENUS))
#define RSM_HOTBAR_SLOT_SPRITE_OFFSET_PIXELS (RSM_GUI_SCALING_FACTOR * 10)
#define RSM_INVENTORY_SLOT_SPRITE_OFFSET_PIXELS (RSM_GUI_SCALING_FACTOR * 8)
#define RSM_COMMAND_TEXT_SCALING (RSM_GUI_SCALING_FACTOR * RSM_COMMAND_TEXT_SIZE)

#define NMEMB_VERTEX (sizeof(Vertex) / sizeof(float))

#define RSM_MAX_BLOCKMESH_VERTICES 1024
#define RSM_MAX_BLOCKMESH_INDICES 2048
#define RSM_MAX_PATH_NAME_LENGTH 512
#define RSM_MAX_SHADER_INFOLOG_LENGTH 512
#define RSM_MAX_BLOCKMESH_TEXTURETILES 8
#define RSM_MAX_COMMAND_LENGTH 64
#define RSM_MAX_COMMAND_LOG_LINES 32

/* Pack Blockdata into uint64_t before saving to disk */
#define RSM_SAVE_IDSHIFT 43
#define RSM_SAVE_VARIANTSHIFT 35
#define RSM_SAVE_ROTATIONSHIFT 32
#define RSM_SAVE_METADATASHIFT 0

#define RSM_BIT_COLLISION (1UL << 0) /* Collidable */
#define RSM_BIT_ROTATION (1UL << 1) /* Rotatable */
#define RSM_BIT_CULLFACES (1UL << 2) /* Cull triangles if neighbors hide faces (needs to match fullblock mesh) */
#define RSM_BIT_CONDUCTOR (1UL << 3) /* Can be hard-powered */
#define RSM_BIT_TOPSUPPORTED (1UL << 4) /* Needs support underneath */
#define RSM_BIT_SIDESUPPORTED (1UL << 5) /* Needs support from the sides */

#define TYPEFACE_PATH "typefaces/"
#define RESOURCE_BASE_PATH "textures/"
#define TEXTURE_BLOCK_PATH "blocks/"
#define TEXTURE_GUI_PATH "gui/"
#define SAVES_PATH "saves/"
#define WORLD_PATH "world"
#define FONT_PATH "liberation-mono/LiberationMono-Regular.ttf"
#define BLOCKMAP_PATH "blockmap.txt"
#define GUIMAP_PATH "guimap.txt"
#define MESH_EXTENSION ".mesh"
#define TEXTURE_EXTENSION ".png"
#define BOUNDINGBOX_EXTENSION ".boundingbox"
#define LAYOUT_EXTENSION ".layout"

typedef enum RSM_EXITCODE {
	RSM_EXIT_NORMAL = 0,
	RSM_EXIT_INITFAIL,
	RSM_EXIT_GLERROR,
	RSM_EXIT_EXCBUF,
	RSM_EXIT_NOBLOCKMAP,
	RSM_EXIT_NOMESHDATA,
	RSM_EXIT_NOBOUNDINGBOXDATA,
	RSM_EXIT_NOTEXTURE,
	RSM_EXIT_NOLAYOUT,
	RSM_EXIT_BADTEXTURE,
	RSM_EXIT_BADVERTEXDATA,
	RSM_EXIT_BADBOUNDINGBOXDATA,
	RSM_EXIT_NOCHUNK,
	RSM_EXIT_THREADFAIL,
	RSM_EXIT_TEXTFAIL,
	RSM_EXIT_NOSAVE
} RSM_EXITCODE;

#endif
