#ifndef RSMLAYOUT_H
#define RSMLAYOUT_H

#include <glad/glad.h>
#include <GLFW/glfw3.h>
#include "usfstd.h"

#define DEFAULT_SCREEN_WIDTH 1920
#define DEFAULT_SCREEN_HEIGHT 1080
#define RSM_NAME "Redsim V0.8"

extern f32 RSM_FLY_ACCELERATION;
extern f32 RSM_FLY_X_ACCELERATION;
extern f32 RSM_FLY_Y_ACCELERATION;
extern f32 RSM_FLY_Z_ACCELERATION;
extern f32 RSM_FLY_FRICTION;
extern f32 RSM_FLY_SPEED_CAP;

/* KEYBINDS */
#define RSM_KEY_CTRL_EXIT GLFW_KEY_Q
#define RSM_KEY_MENU GLFW_KEY_ESCAPE
#define RSM_KEY_INVENTORY GLFW_KEY_E
#define RSM_KEY_COMMAND 0x74 /* ASCII 't' */
#define RSM_KEY_CTRL_CLEARLOG GLFW_KEY_R
#define RSM_KEY_FORWARD GLFW_KEY_W
#define RSM_KEY_BACKWARD GLFW_KEY_S
#define RSM_KEY_RIGHT GLFW_KEY_D
#define RSM_KEY_LEFT GLFW_KEY_A
#define RSM_KEY_DOWN GLFW_KEY_LEFT_SHIFT
#define RSM_KEY_UP GLFW_KEY_SPACE
#define RSM_KEY_FORCEPLACE GLFW_KEY_F
#define RSM_BUTTON_LEFTCLICK GLFW_MOUSE_BUTTON_LEFT
#define RSM_BUTTON_RIGHTCLICK GLFW_MOUSE_BUTTON_RIGHT
#define RSM_BUTTON_MIDDLECLICK GLFW_MOUSE_BUTTON_MIDDLE

#define RSM_COMMAND_PREFIX ":"
#define RSM_COMMAND_CURSOR "_"

#define RSM_KEY_HOTBAR_INCREMENT GLFW_KEY_X
#define RSM_KEY_HOTBAR_DECREMENT GLFW_KEY_Z
#define RSM_KEY_HOTSLOT0 GLFW_KEY_1
#define RSM_KEY_HOTSLOT1 GLFW_KEY_2
#define RSM_KEY_HOTSLOT2 GLFW_KEY_3
#define RSM_KEY_HOTSLOT3 GLFW_KEY_4
#define RSM_KEY_HOTSLOT4 GLFW_KEY_5
#define RSM_KEY_HOTSLOT5 GLFW_KEY_6
#define RSM_KEY_HOTSLOT6 GLFW_KEY_7
#define RSM_KEY_HOTSLOT7 GLFW_KEY_8
#define RSM_KEY_HOTSLOT8 GLFW_KEY_9
#define RSM_KEY_HOTSLOT9 GLFW_KEY_0

extern f32 RSM_MOUSE_SENSITIVITY;

#define RSM_HOTBAR_SLOTS 10
#define RSM_HOTBAR_COUNT 2

#define RSM_INVENTORY_SLOTS_HORIZONTAL 12
#define RSM_INVENTORY_SLOTS_VERTICAL 2
#define RSM_INVENTORY_SUBMENUS 4

#define RSM_FPS 240.0f
#define FPS_CAP true
#define VSYNC true
#define RSM_MAX_PROCESSORS 512

#define CHUNKSIZE 32
extern f32 RSM_REACH;
extern f32 RSM_FOV;
extern f32 RSM_LOADING_DISTANCE;
extern f32 RSM_RENDER_DISTANCE;
extern f32 RSM_NEARPLANE;

extern f32 RSM_COMMAND_POS_X_PIXELS;
extern f32 RSM_COMMAND_POS_Y_PIXELS;
extern f32 RSM_COMMAND_TEXT_SIZE;

extern f32 RSM_NOCLIP;
extern f32 RSM_AIRPLACE;

extern f32 RSM_VISUALSIM;
extern f32 RSM_ENABLESIM;
extern f32 RSM_TICKRATE;
extern f32 RSM_TICKSTEP;

#define PLAYER_BOUNDINGBOX_RELATIVE_CORNER ((vec3) {-0.3f, -1.6f, -0.3f})
#define PLAYER_BOUNDINGBOX_DIMENSIONS ((vec3) {0.6f, 1.8f, 0.6f})

#define RSM_TEXTURE_PADDING 0.01f
#define RSM_BLOCK_TEXTURE_SIZE_PIXELS 32
#define RSM_GUI_TEXTURE_SIZE_PIXELS 64
#define RSM_SPRITE_TEXTURE_SIZE_PIXELS 16
#define RSM_CHARACTER_TEXTURE_SIZE_PIXELS 32

extern f32 RSM_DEFAULT_GUI_SCALING_FACTOR;
#define RSM_GUI_SCALING_FACTOR (RSM_DEFAULT_GUI_SCALING_FACTOR \
	* (((f32)screenWidth_/DEFAULT_SCREEN_WIDTH + (f32) screenHeight_/DEFAULT_SCREEN_HEIGHT)/2.0f))
#define RSM_CROSSHAIR_SIZE_PIXELS (RSM_GUI_SCALING_FACTOR * 32)
#define RSM_HOTBAR_SLOT_SIZE_PIXELS (RSM_GUI_SCALING_FACTOR * 64)
#define RSM_INVENTORY_SLOT_SIZE_PIXELS (RSM_GUI_SCALING_FACTOR * 64)
#define RSM_INVENTORY_ICON_SIZE_PIXELS (RSM_INVENTORY_SLOT_SIZE_PIXELS \
		* (RSM_INVENTORY_SLOTS_HORIZONTAL / RSM_INVENTORY_SUBMENUS))
#define RSM_HOTBAR_SLOT_SPRITE_OFFSET_PIXELS (RSM_GUI_SCALING_FACTOR * 10)
#define RSM_INVENTORY_SLOT_SPRITE_OFFSET_PIXELS (RSM_GUI_SCALING_FACTOR * 8)
#define RSM_COMMAND_TEXT_SCALING (RSM_GUI_SCALING_FACTOR * RSM_COMMAND_TEXT_SIZE)

#define NMEMB_VERTEX 8

#define RSM_MAX_BLOCKMESH_VERTICES 1024
#define RSM_MAX_BLOCKMESH_INDICES 2048
#define RSM_MAX_BLOCKMESH_TEXTURETILES 8
#define RSM_MAX_PATH_NAME_LENGTH 512
#define RSM_MAX_SHADER_INFOLOG_LENGTH 512
#define RSM_MAX_COMMAND_LENGTH 64
#define RSM_MAX_COMMAND_LOG_LINES 32

/* Pack Blockdata into uint64_t before saving to disk */
#define RSM_SAVE_HEADERSZ (sizeof(vec3) + sizeof(u64 [RSM_HOTBAR_COUNT][RSM_HOTBAR_SLOTS][2]))
#define RSM_SAVE_CHUNKSTRIDE (sizeof(u64) + CHUNKSIZE*CHUNKSIZE*CHUNKSIZE * sizeof(u32))
#define RSM_SAVE_
#define RSM_SAVE_IDSHIFT 24
#define RSM_SAVE_IDMASK 0xFF
#define RSM_SAVE_VARIANTSHIFT 16
#define RSM_SAVE_VARIANTMASK 0xFF
#define RSM_SAVE_ROTATIONSHIFT 8
#define RSM_SAVE_ROTATIONMASK 0xFF
#define RSM_SAVE_METADATASHIFT 0
#define RSM_SAVE_METADATAMASK 0xFF

/* Block flags */
#define RSM_BIT_COLLISION (U64(1) << 0) /* Collidable */
#define RSM_BIT_ROTATION (U64(1) << 1) /* Rotate on placement */
#define RSM_BIT_CULLFACES (U64(1) << 2) /* Cull triangles if neighbors occlude (needs to match fullblock mesh) */
#define RSM_BIT_CONDUCTOR (U64(1) << 3) /* Can be hard-powered */
#define RSM_BIT_TOPSUPPORTED (U64(1) << 4) /* Needs support underneath */
#define RSM_BIT_SIDESUPPORTED (U64(1) << 5) /* Needs support from the sides */
#define RSM_BIT_WIRECONNECT_ALL (U64(1) << 6) /* Connects to wires from all directions */
#define RSM_BIT_WIRECONNECT_LINE (U64(1) << 7) /* Connects to wires only from front and back */

/* Simulation */
#define RSM_NATURAL_DECAY 1
#define RSM_MAX_SS 255
#define RSM_WIREFILL_READWRITE 0
#define RSM_WIREFILL_READONLY 1

/* Floodfill flags */
#define RSM_LINKFLAG_READ (U8(1) << 0)
#define RSM_LINKFLAG_WRITE_PRIMARY (U8(1) << 1)
#define RSM_LINKFLAG_WRITE_SECONDARY (U8(1) << 2)

#define TYPEFACE_PATH "typefaces/"
#define RESOURCE_BASE_PATH "textures/"
#define TEXTURE_BLOCK_PATH "blocks/"
#define TEXTURE_GUI_PATH "gui/"
#define SAVES_PATH "saves/"
#define DEFAULT_SAVE_NAME "world"
#define FONT_PATH "liberation-mono/LiberationMono-Regular.ttf"
#define BLOCKMAP_PATH "blockmap.txt"
#define GUIMAP_PATH "guimap.txt"
#define MESH_EXTENSION ".mesh"
#define TEXTURE_EXTENSION ".png"
#define BOUNDINGBOX_EXTENSION ".boundingbox"
#define LAYOUT_EXTENSION ".layout"

typedef enum RSM_EXITCODE {
	RSM_EXIT_NORMAL = 0,
	RSM_EXIT_INITFAIL,
	RSM_EXIT_GLERROR,
	RSM_EXIT_EXCBUF,
	RSM_EXIT_NOBLOCKMAP,
	RSM_EXIT_NOGUIMAP,
	RSM_EXIT_NOMESHDATA,
	RSM_EXIT_NOBOUNDINGBOXDATA,
	RSM_EXIT_NOTEXTURE,
	RSM_EXIT_NOLAYOUT,
	RSM_EXIT_BADTEXTURE,
	RSM_EXIT_BADVERTEXDATA,
	RSM_EXIT_BADBOUNDINGBOXDATA,
	RSM_EXIT_NOCHUNK,
	RSM_EXIT_THREADFAIL,
	RSM_EXIT_TEXTFAIL,
	RSM_EXIT_NOSAVE
} RSM_EXITCODE;

#endif
